modLoader="javafml"
loaderVersion="[40,)"
license="Not specified"

[[mods]]
modId="bou"
version="1.0.0"
displayName="Beasts of Unburden"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="IggiEastwind & BakaSaka"
description="Villagers & animals combine to make new traders and personal vendors."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bou]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration